# Global properties applied to all blocks
color=#cdd6f4
separator=true
separator_block_width=15

[sys_monitor]
command=/home/anidevwired/.config/i3/scripts/load.sh
interval=5
markup=pango

[network]
command=/home/anidevwired/.config/i3/scripts/network.sh
interval=5
markup=pango

[disk]
command=/home/anidevwired/.config/i3/scripts/disk.sh
interval=30
label= 
color=#b4befe

[volume]
command=wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2 * 100)"%"}'
interval=once
signal=10
label= 
color=#b4befe

[date]
command=date '+%b %d %H:%M'
interval=5
label= 
color=#b4befe