# xss-lock
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# Display Setting
exec --no-startup-id xrandr --output HDMI-1 --mode 1920x1080 --rate 100.00 --primary

# NetworkManager
exec --no-startup-id nm-applet

# Authentication agent
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Feh Wallpaper
exec_always --no-startup-id feh --bg-scale /home/anidevwired/Pictures/Wallpapers/arch.png

# Notification-Manger
exec --no-startup-id dunst -config ~/.config/dunst/dunstrc
