# =====================================================================
# Dark Pallet
# =====================================================================
# Base Backgrounds
set $bg-opaque  #1e1e2ecc
set $surface1   #313244
set $crust      #11111b

# Accents & Texts
set $lavender   #b4befe
set $text       #cdd6f4
set $subtext0   #a6adc8
set $red        #f38ba8

# =====================================================================
# Resize Mode
# =====================================================================
mode "resize" {
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}
bindsym $mod+r mode "resize"

# =====================================================================
# Window Border Colors
# =====================================================================
#                       border      background  text        indicator   child_border
client.focused          $lavender   $crust      $text       $lavender   $lavender
client.unfocused        $surface1   $bg-opaque  $subtext0   $surface1   $surface1
client.focused_inactive $surface1   $bg-opaque  $subtext0   $surface1   $surface1
client.urgent           $red        $red        $text       $red        $red

hide_edge_borders both

# =====================================================================
# Status Bar
# =====================================================================
bar {
    status_command i3blocks -c /home/anidevwired/.config/i3/scripts/i3blocks.conf
    font pango:JetBrainsMono Nerd Font Propo, FontAwesome 8
    
    tray_output primary

    colors {
        background $crust
        statusline $lavender
        separator  $subtext0
        
        #                  border      background   text
        focused_workspace  $lavender   $surface1    $text
        inactive_workspace $surface1   $crust       $subtext0212
        urgent_workspace   $red        $red         $text
        
        # binding mode
        binding_mode    $red    $surface1   $red
    }
}